### ISSUE TITLE
[BUG] Syntax highlighting not working for set to

### ISSUE THREAD

**Issue by kylehoover** [jonnyboyC/kos-language-server#109] opened 2019-09-15 05:10 UTC
**Describe the bug**
Syntax highlighting for `set` and `to` is not working in the outer file scope, but works fine in any curly-brace block scope.

**To Reproduce**
1. Replicate the screenshot below in any `.ks` file.

**Expected behavior**
Syntax highlighting for `set` and `to` should work in any scope.

**Screenshots**
![kos-set-to-bug](https://user-images.githubusercontent.com/16613233/64916856-963f7580-d744-11e9-89fd-a66a08f7a083.png)

**Editor (please complete the following information):**
 - OS: Windows
 - Editor: VS Code 1.38.1
 - Extension Version: 0.11.0

**Comment by jonnyboyC** [comment] 2019-09-17 16:14
Thanks for reporting! should be a quick fix

**Comment by jonnyboyC** [comment] 2019-09-17 17:08
So a quick test on my ubuntu machine didn't replicate the issue but let me try later today on my windows machine to see if I can get it reproduced

**Comment by jonnyboyC** [comment] 2019-09-18 11:36
This is what appears on my windows 10 machine. Very similar appears in Ubuntu. Did this only start occurring after updating to 0.11.0? I may still look into tightening up the grammar but I'd mostly be working in the dark if I can't reproduce it.

![image](https://user-images.githubusercontent.com/5347312/65145144-73c88900-d9de-11e9-83f7-3c40d0906755.png)

**Comment by kylehoover** [comment] 2019-09-19 02:20
I just switched the color theme to **Default Dark +** (which it looks like you're using) and it shows up the exact same as yours, which makes it seem the issue is with the color theme I'm using and not the grammar. Sorry for the false alarm!

**Comment by jonnyboyC** [comment] 2019-09-20 13:08
No problem! the grammar files are pretty tricky and I have found like 5-10 little things in the last couple months so no worries. I'll close this for now but if you find this in some other context feel free to reopen it

**Closed by jonnyboyC** 2019-09-20 13:08 UTC
